[2024-09-11T19:11:47.168+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T19:11:47.213+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: generate_and_anonymize_dag.generate_csv manual__2024-09-11T19:06:22.856610+00:00 [queued]>
[2024-09-11T19:11:47.237+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: generate_and_anonymize_dag.generate_csv manual__2024-09-11T19:06:22.856610+00:00 [queued]>
[2024-09-11T19:11:47.239+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-09-11T19:11:47.298+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_csv> on 2024-09-11 19:06:22.856610+00:00
[2024-09-11T19:11:47.753+0000] {standard_task_runner.py:72} INFO - Started process 98 to run task
[2024-09-11T19:11:48.084+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'generate_and_anonymize_dag', 'generate_csv', 'manual__2024-09-11T19:06:22.856610+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/generate_and_anonymize_dag/generate_and_anonymize_dag.py', '--cfg-path', '/tmp/tmp4e50dfv4']
[2024-09-11T19:11:48.088+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask generate_csv
[2024-09-11T19:11:48.832+0000] {task_command.py:467} INFO - Running <TaskInstance: generate_and_anonymize_dag.generate_csv manual__2024-09-11T19:06:22.856610+00:00 [running]> on host ea5e1f9c96ae
[2024-09-11T19:11:49.081+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='generate_and_anonymize_dag' AIRFLOW_CTX_TASK_ID='generate_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T19:06:22.856610+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T19:06:22.856610+00:00'
[2024-09-11T19:11:49.083+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T19:11:49.521+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/generate_and_anonymize_dag/generate_and_anonymize_dag.py", line 18, in generate_csv_task
    raise Exception(f"CSV generation failed with error: {result.stderr}")
Exception: CSV generation failed with error: Traceback (most recent call last):
  File "/opt/airflow/dags/generate_and_anonymize_dag/generate_csv.py", line 3, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'

[2024-09-11T19:11:49.569+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=generate_and_anonymize_dag, task_id=generate_csv, run_id=manual__2024-09-11T19:06:22.856610+00:00, execution_date=20240911T190622, start_date=20240911T191147, end_date=20240911T191149
[2024-09-11T19:11:49.631+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T19:11:49.633+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 27 for task generate_csv (CSV generation failed with error: Traceback (most recent call last):
  File "/opt/airflow/dags/generate_and_anonymize_dag/generate_csv.py", line 3, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
; 98)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/generate_and_anonymize_dag/generate_and_anonymize_dag.py", line 18, in generate_csv_task
    raise Exception(f"CSV generation failed with error: {result.stderr}")
Exception: CSV generation failed with error: Traceback (most recent call last):
  File "/opt/airflow/dags/generate_and_anonymize_dag/generate_csv.py", line 3, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'

[2024-09-11T19:11:49.700+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-11T19:11:49.782+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T19:11:49.816+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
